### PR TITLE
CFD Micro Service

### PR DESCRIPTION
**Pull request by raumildhandhukia**

### CODE REVIEW

**Review by amarjeet-singh-1304 — CHANGES_REQUESTED** [review]
I can see there are two .eslintrc file in this PR one with .js extension and one with .json extension. Please correct this

**Comment by raumildhandhukia** [comment]
> I can see there are two .eslintrc file in this PR one with .js extension and one with .json extension. Please correct this

Removed .eslintrc.json file. Updated Functionality of CFD with Task History.

**Review by amarjeet-singh-1304 — APPROVED** [review]
Looks good

**Review by skuma251 — APPROVED** [review]
looks good

**Pull request merged**
